### ISSUE TITLE
Enhancement: single bit tests.

### ISSUE THREAD

**Issue by petersbingham** [lborgav/angular-bitwise-filter#2]
Can specify a bit number and have that tested against the field (rest of field zero). Just for convenience, especially since angular doesn't seem to allow literal ints in hex format.
eg, to test third bit:
```
<span ng-if="isActiveBit | bitwiseANDbit : 3">
	Show this!
</span>
```

I can make this change and submit PR.

**Comment by lborgav** [comment]
Hi @petersbingham. If you have time to do it, ok for me

**Comment by petersbingham** [comment]
I'm going to do this hopefully soon. If it passes your review I hope you can publish.
